version: '2'
services:
    alpha-app:
        image: alpha
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://alpha-postgresql:5432/alpha
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    alpha-postgresql:
        extends:
            file: postgresql.yml
            service: alpha-postgresql
